#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & polybar & picom & feh --bg-fill .backgrounds/doom.bmp & xfce4-clipman & xfce4-power-manager & nm-applet & stalonetray & $HOME/eww/target/release/eww daemon & $HOME/.config/eww/src/a.out &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8

bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
